### ISSUE TITLE
JDK 11 and maven 3.6.3 build problem in tests

### ISSUE THREAD

**Issue by mareknovotny** [kiegroup/kogito-editors-java#24]
Running `mvn clean install -B`
where 
```
 (main) mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/mnovotny/apps/apache-maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-16-generic", arch: "amd64", family: "unix"
```

and tests shows used old jdk sun.misc.GC class:
```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ kie-wb-common-stunner-bpmn-emf ---
[WARNING] The parameter forkMode is deprecated since version 2.14. Use forkCount and reuseForks instead.
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.jbpm.Bpmn2ResourceTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.131 s - in org.eclipse.jbpm.Bpmn2ResourceTest
[INFO] Running org.eclipse.emf.ecore.util.BasicExtendedMetaDataTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.82 s - in org.eclipse.emf.ecore.util.BasicExtendedMetaDataTest
[INFO] Running org.eclipse.emf.ecore.xmi.util.GwtDOMHandlerTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.225 s - in org.eclipse.emf.ecore.xmi.util.GwtDOMHandlerTest
[INFO] Running org.eclipse.emf.ecore.xmi.resource.xml.XMLSaveTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.075 s - in org.eclipse.emf.ecore.xmi.resource.xml.XMLSaveTest
[INFO] Running org.eclipse.emf.ecore.xmi.resource.xml.XMLHelperTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.925 s - in org.eclipse.emf.ecore.xmi.resource.xml.XMLHelperTest
[INFO] Running org.kie.workbench.common.stunner.bpmn.client.emf.Bpmn2MarshallingTest
[ERROR] jreLeakPrevention.gcDaemonFail
java.lang.ClassNotFoundException: sun.misc.GC
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.jreLeakPrevention(JettyLauncher.java:899)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:722)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:636)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:898)
	at com.google.gwt.junit.JUnitShell.getUnitTestShell(JUnitShell.java:707)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:681)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[main] INFO org.eclipse.jetty.util.log - Logging initialized @2062ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.14.v20151106
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started c.g.g.j.@1fde5d22{/,file:/home/mnovotny/projects/git/KOGITO/kogito-editors-java/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/war/,AVAILABLE}{/home/mnovotny/projects/git/KOGITO/kogito-editors-java/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/war}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@41d426b5{HTTP/1.1}{0.0.0.0:35557}
[main] INFO org.eclipse.jetty.server.Server - Started @2598ms
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 138.493 s <<< FAILURE! - in org.kie.workbench.common.stunner.bpmn.client.emf.Bpmn2MarshallingTest
[ERROR] testUnmarshallSomeProcess(org.kie.workbench.common.stunner.bpmn.client.emf.Bpmn2MarshallingTest)  Time elapsed: 138.423 s  <<< ERROR!
java.lang.RuntimeException: Unexpected error reading resource 'file:/home/mnovotny/projects/git/KOGITO/kogito-editors-java/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/target/classes/org/eclipse/bpmn2/MessageEventDefinition.java'
	at com.google.gwt.dev.javac.CompilationUnitBuilder$ResourceCompilationUnitBuilder.doGetSource(CompilationUnitBuilder.java:150)
	at com.google.gwt.dev.javac.CompilationUnitBuilder.getSource(CompilationUnitBuilder.java:285)
	at com.google.gwt.dev.javac.JdtCompiler$Adapter.getContents(JdtCompiler.java:148)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11943)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11915)
	at com.google.gwt.dev.javac.JdtCompiler$ParserImpl.parse(JdtCompiler.java:204)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:10325)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:840)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:444)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1020)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:322)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1352)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1317)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:681)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.io.FileNotFoundException: /home/mnovotny/projects/git/KOGITO/kogito-editors-java/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/target/classes/org/eclipse/bpmn2/MessageEventDefinition.java (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.google.gwt.dev.resource.impl.FileResource.openContents(FileResource.java:71)
	at com.google.gwt.dev.javac.CompilationUnitBuilder$ResourceCompilationUnitBuilder.doGetSource(CompilationUnitBuilder.java:139)
	... 36 more

[ERROR] testMarshallSomeProcess(org.kie.workbench.common.stunner.bpmn.client.emf.Bpmn2MarshallingTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
	at com.google.gwt.junit.JUnitShell.checkTestClassInCurrentModule(JUnitShell.java:724)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1361)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1317)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:681)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by caponetto** [comment]
Hi @mareknovotny, thanks for reporting these errors.

For the first error, `[ERROR] jreLeakPrevention.gcDaemonFail`, there is nothing much we can do about it right now, 
although it can be safely ignored. Please see https://github.com/gwtproject/gwt/issues/9561.

For the second and third errors, I'd say this is something with your env as we are not seeing such errors on CI.
Anyway, I'll take a better look at this. Please share any new information about it.

**Comment by mareknovotny** [comment]
just fyi the repository readme ask to use JDK 11 so what version is used in CI? I think this report is to signal in the future even the CI can have this problem

**Comment by mareknovotny** [comment]
well, i don't argue on that.  the important thing is what version of jdk 11
